# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUlR0vSkwTPcsQ5_hhQoMQNU4E6h5Heg
"""

import streamlit as st
import json

# --- 1. Page Config ---
st.set_page_config(page_title="MedQuiz Prep", page_icon="⚕️", layout="centered")

# --- 2. Load Data ---
@st.cache_data
def load_data():
    try:
        with open("questions.json", "r", encoding="utf-8") as file:
            return json.load(file)
    except FileNotFoundError:
        st.error("Error: 'questions.json' not found. Please create the file in the same directory.")
        return []

questions = load_data()

# --- 3. Session State Initialization ---
if 'current_q' not in st.session_state:
    st.session_state.current_q = 0
if 'user_answers' not in st.session_state:
    st.session_state.user_answers = [None] * len(questions)
if 'quiz_submitted' not in st.session_state:
    st.session_state.quiz_submitted = False

# --- 4. Helper Functions ---
def next_q():
    if st.session_state.current_q < len(questions) - 1:
        st.session_state.current_q += 1

def prev_q():
    if st.session_state.current_q > 0:
        st.session_state.current_q -= 1

def submit_quiz():
    st.session_state.quiz_submitted = True

def reset_quiz():
    st.session_state.current_q = 0
    st.session_state.user_answers = [None] * len(questions)
    st.session_state.quiz_submitted = False

# --- 5. Main UI ---
if not questions:
    st.stop()

st.title("⚕️ Medical Quiz Prep")
st.markdown("---")

# Progress Bar
progress = (st.session_state.current_q + 1) / len(questions)
st.progress(progress)
st.write(f"**Question {st.session_state.current_q + 1} of {len(questions)}**")

# Display Question
q_data = questions[st.session_state.current_q]
st.subheader(q_data["question"])

# Handle Radio Button State
current_answer = st.session_state.user_answers[st.session_state.current_q]
try:
    index = q_data["options"].index(current_answer) if current_answer in q_data["options"] else None
except ValueError:
    index = None

# Display Options
selected_option = st.radio(
    "Choose your answer:",
    options=q_data["options"],
    index=index,
    key=f"q_{st.session_state.current_q}",
    disabled=st.session_state.quiz_submitted
)

# Save answer to state
st.session_state.user_answers[st.session_state.current_q] = selected_option

st.markdown("---")

# --- 6. Navigation Buttons ---
col1, col2, col3 = st.columns([1, 1, 1])

with col1:
    if st.session_state.current_q > 0:
        st.button("⬅️ Previous", on_click=prev_q)

with col3:
    if st.session_state.current_q < len(questions) - 1:
        st.button("Next ➡️", on_click=next_q)
    elif st.session_state.current_q == len(questions) - 1 and not st.session_state.quiz_submitted:
        st.button("✅ Submit Quiz", on_click=submit_quiz, type="primary")

# --- 7. Results Screen ---
if st.session_state.quiz_submitted:
    st.markdown("## 📊 Quiz Results")

    score = 0
    for i, q in enumerate(questions):
        correct = q["correct_answer"]
        user_ans = st.session_state.user_answers[i]

        if user_ans == correct:
            score += 1
            st.success(f"**Q{i+1}: Correct!** {correct}")
        else:
            st.error(f"**Q{i+1}: Incorrect.**")
            st.write(f"Your answer: *{user_ans if user_ans else 'No answer provided'}*")
            st.write(f"Correct answer: **{correct}**")

    st.metric(label="Final Score", value=f"{score} / {len(questions)}", delta=f"{(score/len(questions))*100:.1f}%")

    st.button("🔄 Retake Quiz", on_click=reset_quiz)